#!/bin/bash

# Alternative: SES Production Access über Support Center beantragen
# Falls der Button in der Console nicht klickbar ist

echo "📧 SES Production Access über Support Center beantragen"
echo "========================================================"
echo ""
echo "Da der Button in der Console nicht klickbar ist, verwende das Support Center:"
echo ""
echo "🔗 Direkter Link zum Support Center:"
echo "   https://console.aws.amazon.com/support/home#/case/create"
echo ""
echo "📋 Schritt-für-Schritt:"
echo ""
echo "1. Gehe zum Support Center (Link oben)"
echo ""
echo "2. Klicke auf 'Create case' oder 'Neuen Fall erstellen'"
echo ""
echo "3. Wähle Falltyp: 'Service limit increase'"
echo ""
echo "4. Fülle das Formular aus:"
echo "   - Limit Type: SES Sending Limits"
echo "   - Region: EU (Frankfurt) / eu-central-1"
echo "   - Limit: SES Production Access"
echo "   - New limit value: 1"
echo ""
echo "5. Use case description (kopiere diesen Text):"
echo ""
echo "--- BEGIN USE CASE ---"
echo "Sending transactional email verification codes for user registration"
echo "in a web application using AWS Cognito. Users register on the website"
echo "and receive verification codes via email to confirm their email addresses."
echo ""
echo "Website URL: https://mawps.netlify.app"
echo "Mail Type: Transactional"
echo "Expected sending volume: Low (< 1000 emails/day)"
echo ""
echo "We ensure compliance with AWS SES policies and best practices for"
echo "email delivery, including proper handling of bounces and complaints."
echo "--- END USE CASE ---"
echo ""
echo "6. Klicke auf 'Submit' oder 'Absenden'"
echo ""
echo "7. Warte auf AWS Genehmigung (meist 24-48 Stunden)"
echo ""
echo "✅ Nach Genehmigung:"
echo "   - E-Mails können an alle E-Mail-Adressen versendet werden"
echo "   - Keine Verifizierung der Empfänger-E-Mail-Adressen mehr nötig"
echo ""

