AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple media service for profile images (presigned PUT) with public GET

Parameters:
  BucketName:
    Type: String
    Default: manuel-weiss-public-media
    Description: S3 bucket for public profile images (GET public, PUT via presign)
  ProfilePrefix:
    Type: String
    Default: public/profile-images/
    Description: Key prefix inside the bucket
  DocumentsPrefix:
    Type: String
    Default: public/documents/
    Description: Key prefix for documents (CV, certificates)

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 256

Resources:
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET, PUT]
            AllowedOrigins: ['*']
            AllowedHeaders: ['*']
            ExposedHeaders: ['ETag']
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Optional: make objects publicly readable (uploads set ACL public-read)
  MediaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MediaBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${MediaBucket.Arn}/*'

  MediaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda-profile-image
      Handler: index.handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref MediaBucket
          REGION: !Ref AWS::Region
          PROFILE_PREFIX: !Ref ProfilePrefix
          DOCUMENTS_PREFIX: !Ref DocumentsPrefix
          PROFILE_TABLE: mawps-user-profiles
      Policies:
        - S3WritePolicy:
            BucketName: !Ref MediaBucket
        - S3ReadPolicy:
            BucketName: !Ref MediaBucket
        - DynamoDBCrudPolicy:
            TableName: mawps-user-profiles
      Events:
        Presign:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /profile-image/upload-url
            Method: POST
        PresignOptions:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /profile-image/upload-url
            Method: OPTIONS
        DocumentPresign:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /document/upload-url
            Method: POST
        DocumentPresignOptions:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /document/upload-url
            Method: OPTIONS
        WebsiteImagesSave:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /website-images
            Method: POST
        WebsiteImagesSaveOptions:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /website-images
            Method: OPTIONS
        WebsiteImagesGet:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /website-images/{userId}
            Method: GET
        WebsiteImagesGetOptions:
          Type: Api
          Properties:
            RestApiId: !Ref MediaApi
            Path: /website-images/{userId}
            Method: OPTIONS

Outputs:
  ApiBaseUrl:
    Description: Invoke URL base
    Value: !Sub 'https://${MediaApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  BucketNameOut:
    Description: Media bucket name
    Value: !Ref MediaBucket




