name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Validate HTML
      run: |
        echo "Validating HTML files..."
        find . -name "*.html" -not -path "./node_modules/*" | head -5
        
    - name: Check File Structure
      run: |
        echo "Checking file structure..."
        ls -la
        echo "Key files present:"
        ls -la *.html | head -3
        
    - name: Build API Docs
      run: npm run build:api-docs
      continue-on-error: true
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-artifacts
        path: |
          docs/api/dist/
          *.html
